# Generated by Django 5.2.1 on 2025-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customeruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False),
        ),
    ]
